### ISSUE TITLE
Show

### ISSUE THREAD

**Issue by alissonandrade2020** [grochavieira/happy-frontend#1]
Bom dia Grocha Vieira.

Cara que massa a aplicação eu fiz mas fiz a aplicação básica, que beleza em Backend e Frontend, poderia me ajudar a fazer essa ?  Ficou sow de bola ! 

Parabéns.. .não queria clonar só tlgd ?  Quero fazer pra aprender, algumas coisas eu ate sei, mas queria tirar as dúvidas como Login, chegando no e-mail e etc... 

Fiquei curioso, estou na turma do Ignite - turma 1 tá fazendo ?

**Comment by grochavieira** [comment]
Olá Alisson, eu poderia te dar algumas direções de como fazer a aplicação, me chama lá no linkedin que fica mais fácil pra gente trocar uma ideia. E só pra você saber, eu não estou fazendo nenhum curso/bootcamp da rocketseat.
